### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint.io#21]
When I released 7.3.0, it looks like the website *did* update (?), but the process failed with this error:

```
phenomic:builder ModuleBuildError: Module build failed: Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/css-loader/index.js?modules&localIdentName=[hash:base64:5]!/Users/davidclark/dev/stylelint.io/node_modules/postcss-loader/index.js!/Users/davidclark/dev/stylelint.io/web_modules/layouts/PageError/index.css:1:63)
    at Module._compile (module.js:409:26)
    at Object.loaderContext.exec (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:88:7)
    at Object.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/extract-text-webpack-plugin/loader.js:97:22)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:403:12
    at DependenciesBlock.onModuleBuildFailed (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at DependenciesBlock.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:228:39)
    at context.callback (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/extract-text-webpack-plugin/loader.js:112:13)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:214:10)
    at /Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/extract-text-webpack-plugin/loader.js:78:5)
    at Compiler.next (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/CachePlugin.js:40:4) +1ms
/Users/davidclark/dev/stylelint.io/node_modules/phenomic/lib/builder/webpack/index.js:17
      throw new Error("webpack build failed with errors");
      ^

Error: webpack build failed with errors
    at /Users/davidclark/dev/stylelint.io/node_modules/phenomic/lib/builder/webpack/index.js:17:13
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/davidclark/dev/stylelint.io/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/davidclark/dev/stylelint.io/node_modules/webpack/node_modules/async/lib/async.js:246:17)
```

Any ideas?

**Comment by MoOx** [comment]
source-map-support is a phenomic dependency, so it looks like npm didn't do it's job correctly.

**Comment by jeddy3** [comment]
> When I released 7.3.0, it looks like the website did update (?)

I've just [deployed](http://stylelint.io/CHANGELOG/) the `7.3.1` version for you.

> Any ideas?

As @MoOx said, can you try running `npm install` again?

**Comment by davidtheclark** [comment]
I did that earlier today. Same issue. I doubt that the problem is just that "npm didn't do it's job correctly". I'm using npm 2.15.11.

**Comment by MoOx** [comment]
phenomic does not support npm@2, it may be the reason :)

**Comment by davidtheclark** [comment]
> phenomic does not support npm@2

Ooooo ... that kind of sucks, right? Because its LTS for npm? Well, either way I guess I'll leave deployment to you @jeddy3.

**Comment by MoOx** [comment]
npm@4 is on track, so maybe it's time to use npm@3, which is the default since node 5 ;)
Anyway, the way phenomic works, it cannot work with npm@2, or it will require more tricks and works.

**Comment by davidtheclark** [comment]
@MoOx I'm using 2 because of my organization, but yeah, will need to switch at some point. In fact, just read the latest release notes and it sounds like 4 will be launched soon (i.e. within a month or so) so 3 will become the new LTS.

**Comment by MoOx** [comment]
You should use nvm so you can easily switch node/npm versions ;)
